name: Exchange.Windows.Applications.FTKImager.Fixed
description: |
    Create an E01 Image of the C drive using FTK Imager (Command Line
    Version)

    SourceDriveToImage usually will be 0 (as in \\.\PHYSICALDRIVE0)
    for the C: drive, on a Windows system.

    If you intend to image the secondary drive, use, for example,
    SourceDriveToImage = 1, for \\.\PHYSICALDRIVE1

author: Eduardo Mattos - @eduardfir, Fixed by Yaniv Radunsky @ 10root cyber security

reference:
  - https://accessdata.com/products-services/forensic-toolkit-ftk/ftkimager

type: CLIENT

tools:
  - name: FTKImager
    url: https://ad-zip.s3.amazonaws.com/FTKImager.3.1.1_win32.zip

precondition: SELECT OS From info() where OS = 'windows'

parameters:
  - name: SourceDriveToImage
    default: "\\\\.\\PHYSICALDRIVE0"

  - name: OutputPath
    default: "D:\\E01"
    description: "(Enter full path with output filename with no extention, can be UNC)"
    
  - name: UploadFiles
    description: "Upload image?"
    type: bool

sources:
  - query: |
      -- get context on target binary
      LET Toolzip <= SELECT FullPath
        FROM Artifact.Generic.Utils.FetchBinary(ToolName="FTKImager", IsExecutable=FALSE)

      LET tmpdir <= tempdir()

      LET _ <= SELECT * FROM unzip(filename=Toolzip.FullPath, output_directory=tmpdir)
                        
      LET FTKExe <= tmpdir + '\\ftkimager.exe'    
      LET cmdline <= filter(list=(
        FTKExe, SourceDriveToImage, OutputPath, "--e01"))

      -- execute payload
        SELECT * FROM execve(argv=cmdline, sep="\n", length=9999999)

  - name: Upload
    query: |
        -- if configured upload image

        SELECT upload(file=OutputPath + ".e01",
            accessor="auto") as Upload
        FROM cmdline
